version: "3.9"
services:
    spring-boot-api:
        image: demo
        container_name: demo
        build:
            context: ./demo
        ports:
            - "9000:80"
    angular-web-app:
        image: angular-web-app
        container_name: angular-web-app
        build:
            context: ./angular-app
        ports:
            - "4200:80"
        depends_on:
            - spring-boot-api